# Generated by Django 5.0.4 on 2024-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner_image",
            field=models.ImageField(
                default="/profile_default.png",
                upload_to="",
                verbose_name="banner image",
            ),
        ),
    ]
